version: '3.6'
services:
  mysqldb:
    container_name: "mysqldb"
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=pa
    volumes:
      - ./mysql:/var/lib/mysql

  nodeapp1:
    container_name: express1
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - 8888:8080 
    restart: always

# dossier mysql à créer avant de docker-compose up -d --build